server:
  port: 8081

spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/zs-permissions
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: false


logging:
  level: debug

