server:
  port: 8081

spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/zs-permissions
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: true
  mail:
    host: smtp.qq.com
    username: 616394599@qq.com
    password: zzbjykpildvqbefh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


permissions:
  redis:
    redisAddress: redis://47.52.207.143:6379

logging:
  config: classpath:logback-spring.xml

