server:
  port: 8081

spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/zs-permissions
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: true

permissions:
  redis:
    redisAddress: redis://47.52.207.143:6379

logging:
  config: classpath:logback-spring.xml

